export default {
  skill: {
    name: 'warp-docs',
    title: 'Warp Design System',
    description:
      'Warp Design System reference docs for components, patterns, framework implementations, and core getting-started and foundation guides.',
    baseUrl: 'https://warp-ds.github.io/docs',
    outputDir: 'skills/warp-docs',
    repository: 'https://github.com/warp-ds/docs',
  },
  components: {
    exclude: [],
    pageOrder: ['overview', 'usage', 'styling', 'accessibility'],
    frameworkOrder: ['react', 'react-19', 'vue', 'elements', 'android', 'ios'],
  },
  patterns: {
    exclude: [],
    pageOrder: ['overview', 'usage', 'styling', 'accessibility'],
    frameworkOrder: ['react', 'react-19', 'vue', 'elements', 'android', 'ios'],
  },
  guides: {
    root: ['index.md', 'pre-migrating.md'],
    getStarted: [
      'get-started/index.md',
      'get-started/mission-values-principles/index.md',
      'get-started/developers/web/index.md',
      'get-started/developers/web/web-components.md',
      'get-started/developers/web/react.md',
      'get-started/developers/web/vue.md',
      'get-started/developers/web/elements.md',
      'get-started/developers/web/custom-components/index.md',
      'get-started/developers/web/migrate-from-fabric/index.md',
      'get-started/developers/android/index.md',
      'get-started/developers/ios/index.md',
      'get-started/designers/warp-in-figma/index.md',
      'get-started/designers/designing-for-multibrand/index.md',
      'get-started/designers/custom-components/index.md',
      'get-started/designers/migrate-from-fabric/index.md',
    ],
    help: ['help/faq/index.md', 'help/support/index.md'],
    foundations: [
      'foundations/index.md',
      'foundations/accessibility/index.md',
      'foundations/brands/index.md',
      'foundations/dark-mode/index.md',
      'foundations/elevation/index.md',
      'foundations/font-weights/index.md',
      'foundations/illustrations/index.md',
      'foundations/motion/index.md',
      'foundations/typography/index.md',
    ],
    foundationDirectories: ['foundations/tokens', 'foundations/css-classes'],
  },
};
